name: Deploy Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: Debug PATH
        run: echo $PATH
        
      - name: Copy build artifacts to EC2
        run: |
          # Replace EC2_INSTANCE_IP with your actual EC2 instance's public IP or domain name
          # Replace USER_NAME with your server's username
          # Replace /path/to/your/app with the location of your Express.js app
          scp -r ./dist package.json package-lock.json ${{ secrets.USER_NAME }}@${{ secrets.EC2_INSTANCE_IP }}:/home/${{ secrets.USER_NAME }}/app
        env:
          # API_KEY: ${{ secrets.API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Node.js dependencies on EC2
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.EC2_INSTANCE_IP }} "export NVM_DIR=~/.nvm && source ~/.nvm/nvm.sh && cd /home/${{ secrets.USER_NAME }}/app && npm install"
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Start Express.js server on EC2
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.EC2_INSTANCE_IP }} "source ~/.nvm/nvm.sh && cd /home/${{ secrets.USER_NAME }}/app && pm2 start dist/index.js --watch"
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
